language: java

before_install:
  - chmod +x mvnw


addons:
  sonarcloud:
    organization: "andresfr09"
    token:
      secure: YEYiIAgvykiU297ZAzzIZkR9Cvrt4ZyUhxqH6Og+fXgmxsjOJQDedpCLLxpisDMgx/VlJlP4itEaWgw0WO1dzX62tbdPTL1ZkW8HGdpNDHnEtUSgGBhONn/1zM7FXGL39yVMrVX7nlW6O3P2eLOppZ/vek03s7X4mb2hfbhF5P5jK1nX/1SQyA7/rObrYI7
  fZowg+nEffYB1Olyxo0E6ojb9gyarKUHX7DsD2gmBsBbF3/s9l7Ff4VIH66BFS+XaSsu6mAQI2PEh65E4ykJFl3z5lyGv1ytox2if27UMRX/NCdYe2GmR/XC9TVT/fdLngke+tYt++MVRbLgLUfq2g9rSaYBMa88dpQS/CVvBAF2MBHk4GxXCh7TMSMLuob/qgktl49iQj
  pouQ8l4s/DkJrl983fsDg9bZaGGUtZAN2KWKxKHptFwOAaOnIlbWHe5oualXyg5LMMIdQOjGMSxCASIyqmsXkgBVp+Ecwd9ecQT2tb0tAJ8d7zn3V/pjD8dFGclldzG8i/hYB06tD8JRJGyokDWiRj4CIEkOU8SG5wozhWTC3O9N1FUE3q8I90+e7xrZEAwy03x1bLuUR9
  WFAePn3DpXZP0fH3TyH8GOzJjXJvAxgkyKFuj4WuPcujO5m7i4X2srLca6FybdBa4O1dFy3E1ikEiedlLsCjZ6xc=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
