language: java

before_install:
  - chmod +x mvnw


addons:
  sonarcloud:
    organization: "andresfr09"
    token:
      secure: jufXPRKpFoVKya9VeJmTCKppxM82+XYRsR/XLxPyZ1mzAOpwjnT5fNb50yETURO78RkeSWMZFjPKEAKbLVTiucc8WVnBPW1Er72LO5EyQfw8RRYbuiE1TrrKOh0hdGw5iL/UBkBaePwj5IYr1VhRBgUWJWo2c20zL2W/yPXK/sZLLUhVNlmoHNYQJahsBLg
  URw0ZRp8A6sPgbYVhRyO8/e49+w2E0SOzyoNQjcBg3Gprj1CYavD/vDAFvWWeAhQpFjS7g33bKVi7b50pdU5a8A3vNi7uqPh3G/1+ej8m+LwOgv1zcXWOuYkLHgyljeHDFdk2ReNTBQsxiDb7fEkL+0i1HfwXn0WjjMR+9Be5WczHzkPkhPG2DhUBZnGLnxAjIwyFOUNNE
  tVDvzCKo03XRc1wCbyFbZaL14o+8pY+J25Xy4pdrDAmT22HnxaqcexbxlxS8zv8JflVS9BDDTEwNZBo45SM2uEH9HTp2Dem5AhXqt16NOveKyOyFJ9qpnQe/dgJ2GPn/hvftwij2e++lWiy32ZKwhS6F2v121/dn8AF0XOAngDfeWQ1AdwBIQoMPhhcjI4qX8Av8fegKOT
  rYxlvmMBY3t7lzuo4BThW3WPCTjyHh+YAySjywHSux7+UZERtbwGPTwOmPPzzdPDR5CDaLBE8e8m/mDENU6Udyec=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

    travis encrypt